type NavigationStackParams = {
  SignUpMain: undefined;
  Login: undefined;
  EmailInput: undefined;
  Greet: undefined;
  GroupCodeCreate: undefined;
  GroupCodeInput: undefined;
  GroupCodeShare: undefined;
  NicknameInput: undefined;
  PasswordInput: undefined;
  PhoneInput: undefined;
  PhoneAuth: undefined;
  Main: undefined;
  EditProfile: undefined;
  MapDetail: undefined;
  MyPage: undefined;
  Notice: undefined;
  Record: undefined;
  Home: undefined;
  Map: undefined;
  Feed: undefined;
};
